#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';

use Net::LastFM;

my $username = shift || 'davorg';
my $method   = 'user.getTopArtists';

my $lastfm = Net::LastFM->new(
  api_key    => $ENV{LASTFM_API_KEY},
  api_secret => $ENV{LASTFM_SECRET},
);

my $data = $lastfm->request_signed(
  method => $method,
  user   => $username,
);

my @artists;

for (@{$data->{topartists}{artist}}) {
  next if $_->{playcount} >= 1000;
  next if $_->{playcount} <= 500;

  push @artists, $_->{name};
}

say $artists[ rand @artists ];
